### ISSUE TITLE
Ruby Capstone Kanban Board

### ISSUE THREAD

**Issue by sharon-odhiambo** [sharon-odhiambo/Ruby-Capstone-Project#32]
- Hello, this is the link to our Kanban Board project- https://github.com/sharon-odhiambo/Ruby-Capstone-Project/projects/1
- We are three of us.
Team member1- @sharon-odhiambo 
Team member2 - @businesskaniki 
Team member3- @Hamayounali 

Cheers and Happy Reviewing!

**Comment by prolajumokeoni** [comment]
Hi @Team

Your kanban board setup is complete 👏🏿 


Congratulations! 🎉 
## Highlights
- Good setup 👍🏿 
- Good issue description ✅ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sharon-odhiambo** [comment]
Hi @prolajumokeoni , thank you for the review.
